import Head from 'next/head'

/** Components */

import Navbar from '@components/Navbar/Index'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />
    </div>
  )
}
